# yaml-language-server: $schema=https://raw.githubusercontent.com/GoogleContainerTools/skaffold/main/docs-v2/content/en/schemas/v4beta13.json
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: cnis
manifests:
  kustomize:
    paths:
      - calico
  helm:
    releases:
      - name: cilium
        remoteChart: cilium
        repo: https://helm.cilium.io 
        valuesFiles:
          - cilium/values.yaml
profiles:
  - name: bgp
    manifests:
      rawYaml:
        - calico/bgp/cilium-peers.yaml
        - cilium/bgp/clusterconfig.yaml
        - cilium/bgp/advertisements.yaml
    patches:
      - op: add
        path: /manifests/helm/releases/0/valuesFiles/-
        value: cilium/bgp/values.yaml
---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: route-controller
build:
  artifacts:
    - image: ttl.sh/route-controller
      context: route-controller
      ko: {}
manifests:
  rawYaml:
    - route-controller/deploy/deployment.yaml
